[package]
name = "chapter"
version = "0.1.0"
edition = "2021"

[dependencies]
chapter5 = { path = "chapter5", version = "0.1.0" }
chapter6 = { path = "chapter6", version = "0.1.0" }

[workspace]
members = [
    "chapter5",
    "chapter6"
]
